env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_ORG: ${{ secrets.IBM_CLOUD_ORG }}
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  IBM_CLOUD_SPACE: ${{ secrets.IBM_CLOUD_SPACE }}

runs:
  using: "composite"
  steps:
  # Download and Install IBM Cloud CLI
  - name: Install IBM Cloud CLI
    run: |
      curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
      ibmcloud --version
      ibmcloud config --check-version=false
      ibmcloud plugin install -f cloud-functions
  # Authenticate with IBM Cloud CLI
  - name: Authenticate with IBM Cloud CLI
    run: |
      ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -o "${IBM_CLOUD_ORG}" -s "${IBM_CLOUD_SPACE}"