# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Deploy Actions to IBM Cloud

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_ORG: ${{ secrets.IBM_CLOUD_ORG }}
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  IBM_CLOUD_SPACE: ${{ secrets.IBM_CLOUD_SPACE }}
  CLOUDANT_WRITE_APIKEY: ${{ secrets.CLOUDANT_WRITE_APIKEY }}
  CLOUDANT_READ_APIKEY: ${{ secrets.CLOUDANT_READ_APIKEY }}
  CLOUDANT_URL: ${{ secrets.CLOUDANT_URL }}
  CLOUDANT_HOSTNAME: $${{ secrets.CLOUDANT_HOSTNAME }}
  CLOUD_IAM_URL: $${{ secrets.CLOUD_IAM_URL }}
  REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
  REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
  REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
  REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}

jobs:
  deploy-top-threads-action:
    name: Deploy Reddit Top Threads action
    runs-on: ubuntu-latest
    environment: Test Environment
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Log into IBM Cloud
    - name: IBM Cloud Login
      uses: srijithprabhu/login-ibm-cloud@v0
      with:
        ibm-cloud-api-key: ${{ env.IBM_CLOUD_API_KEY }}
        ibm-cloud-region: ${{ env.IBM_CLOUD_REGION }}
        ibm-cloud-org: ${{ env.IBM_CLOUD_ORG }}
        ibm-cloud-space:  ${{ env.IBM_CLOUD_SPACE }}

    # Deploy to Cloud Functions
    - name: Deploy Top Threads Action
      run: |
        ibmcloud fn deploy --manifest get_subreddit_top_threads_action/manifest.yml

  deploy-reduce-thread-action:
    name: Deploy Reduce Thread Action
    runs-on: ubuntu-latest
    environment: Test Environment
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Log into IBM Cloud
      - name: IBM Cloud Login
        uses: srijithprabhu/login-ibm-cloud@v0
        with:
          ibm-cloud-api-key: ${{ env.IBM_CLOUD_API_KEY }}
          ibm-cloud-region: ${{ env.IBM_CLOUD_REGION }}
          ibm-cloud-org: ${{ env.IBM_CLOUD_ORG }}
          ibm-cloud-space: ${{ env.IBM_CLOUD_SPACE }}

      # Deploy to Cloud Functions
      - name: Deploy Reduce Thread Action
        run: |
          ibmcloud fn deploy --manifest reduce_reddit_thread_action/manifest.yml

  deploy-high-short-interest-action:
    name: Deploy High Short Interest Action
    runs-on: ubuntu-latest
    environment: Test Environment
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Log into IBM Cloud
      - name: IBM Cloud Login
        uses: srijithprabhu/login-ibm-cloud@v0
        with:
          ibm-cloud-api-key: ${{ env.IBM_CLOUD_API_KEY }}
          ibm-cloud-region: ${{ env.IBM_CLOUD_REGION }}
          ibm-cloud-org: ${{ env.IBM_CLOUD_ORG }}
          ibm-cloud-space: ${{ env.IBM_CLOUD_SPACE }}

      # Deploy to Cloud Functions
      - name: Deploy HIgh Short Interest action
        run: |
          ibmcloud fn deploy --manifest high_short_interest_action/manifest.yml

  deploy-send-newsletter-action:
    name: Deploy Send Newsletter Action
    runs-on: ubuntu-latest
    environment: Test Environment
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Log into IBM Cloud
      - name: IBM Cloud Login
        uses: srijithprabhu/login-ibm-cloud@v0
        with:
          ibm-cloud-api-key: ${{ env.IBM_CLOUD_API_KEY }}
          ibm-cloud-region: ${{ env.IBM_CLOUD_REGION }}
          ibm-cloud-org: ${{ env.IBM_CLOUD_ORG }}
          ibm-cloud-space: ${{ env.IBM_CLOUD_SPACE }}

      # Deploy to Cloud Functions
      - name: Deploy Send Newsletter action
        run: |
          ibmcloud fn deploy --manifest send_newsletter_action/manifest.yml